### ISSUE TITLE
プレーンなクラスファイルを用意する

### ISSUE THREAD

**Issue by momeemt** [coins-shinkan23/satysfi-class-coins-shinkan23-pamphlet#6]
章が必要ないページがある（委員紹介など）ので、プレーンなクラスファイルを用意する

**Comment by puripuri2100** [comment]
document関数の引数の`chapter-num`を`int option`にして、`None`が来た場合は章タイトルを外すように設計を変更するなどの方法もありそう

**Comment by momeemt** [comment]
確かに！今日これやってみます
